name: EvolvedFaction
version: '${project.version}'
main: com.thegost.evolvedfaction.EvolvedFaction
api-version: 1.19
authors: [ TheGost ]
description: Pvp-Faction plugin
website: https://github.com/TheGostDev/EvolvedFaction
commands:
  grade:
    description: Manage grade of your server
    aliases:
      - g